upstox:
  api_key: 
  api_secret: 
  redirect_uri: https://127.0.0.1:8080/callback
  access_token: 
zerodha:
  api_key: YOUR_ZERODHA_API_KEY
  api_secret: YOUR_ZERODHA_API_SECRET
  access_token: ''
scheduler:
  update_interval_minutes: 30
  market_open: 09:15
  market_close: '15:30'
app:
  host: 0.0.0.0
  port: 8000
  cors_origins:
  - http://localhost:5173
defaults:
  order_type: MARKET
  default_quantity: 1
  exchange: NSE
